import type { FieldOption, FormField } from '../types/form'

export const FIELD_TYPES: { value: string; label: string }[] = [
  { value: 'text', label: 'Texto' },
  { value: 'number', label: 'Número' },
  { value: 'file', label: 'Arquivo' },
  { value: 'email', label: 'E-mail' },
  { value: 'password', label: 'Senha' },
  { value: 'tel', label: 'Telefone' },
  { value: 'date', label: 'Data' },
  { value: 'select', label: 'Seleção' },
  { value: 'radio', label: 'Radio' },
  { value: 'checkbox', label: 'Checkbox' },
  { value: 'textarea', label: 'Área de Texto' },
]

export const CITY_DB: Record<string, FieldOption[]> = {
  br: [{ value: 'sp', label: 'São Paulo' }, { value: 'rj', label: 'Rio de Janeiro' }],
  ca: [{ value: 'to', label: 'Toronto' }, { value: 'va', label: 'Vancouver' }],
  ar: [{ value: 'ba', label: 'Buenos Aires' }, { value: 'mdz', label: 'Mendoza' }],
}

export const INITIAL_FIELDS: FormField[] = [
  {
    id: 1,
    label: 'Nome',
    default: '',
    type: 'text',
    required: true,
    placeholder: 'Digite seu nome',
    minLength: 3,
    maxLength: 50,
  },
  {
    id: 2,
    label: 'E-mail',
    default: '',
    type: 'email',
    required: true,
    placeholder: 'exemplo@email.com',
  },
  {
    id: 3,
    label: 'Senha',
    default: '',
    type: 'password',
    required: true,
    placeholder: 'Mínimo 8 caracteres',
    minLength: 8,
  },
  {
    id: 4,
    label: 'Idade',
    default: '',
    type: 'number',
    required: false,
    placeholder: 'Ex: 25',
    min: 18,
    max: 120,
  },
  {
    id: 5,
    label: 'Telefone Celular',
    default: '',
    type: 'tel',
    required: true,
    placeholder: '(11) 99999-9999',
    pattern: '^\\([0-9]{2}\\) [0-9]{5}-[0-9]{4}$',
  },
  {
    id: 6,
    label: 'Data de Nascimento',
    default: '',
    type: 'date',
    required: true,
    min: '1900-01-01',
    max: '2026-12-12',
  },
  {
    id: 7,
    label: 'Gênero',
    default: '',
    type: 'select',
    required: true,
    placeholder: 'Selecione uma opção...',
    options: [
      { value: 'M', label: 'Masculino' },
      { value: 'F', label: 'Feminino' },
    ],
  },
  {
    id: 8,
    label: 'Nível de Experiência',
    default: 'pleno',
    type: 'radio',
    required: true,
    options: [
      { value: 'junior', label: 'Júnior' },
      { value: 'pleno', label: 'Pleno' },
      { value: 'senior', label: 'Sênior' },
    ],
  },
  {
    id: 9,
    label: 'Aceito os termos e condições de uso',
    default: false,
    type: 'checkbox',
    required: true,
  },
  {
    id: 10,
    label: 'Biografia ou Observações',
    default: '',
    type: 'textarea',
    required: false,
    placeholder: 'Conte um pouco sobre você...',
    maxLength: 500,
  },
  {
    id: 11,
    label: 'País',
    name: 'country',
    default: '',
    type: 'select',
    required: true,
    placeholder: 'Selecione um país...',
    options: [
      { value: 'br', label: 'Brasil' },
      { value: 'ca', label: 'Canadá' },
      { value: 'ar', label: 'Argentina' },
    ],
  },
  {
    id: 12,
    label: 'Cidade',
    default: '',
    type: 'select',
    required: true,
    placeholder: 'Selecione uma cidade...',
    options: [],
    dependsOn: 'country',
    disabled: true,
  },
]
